### ISSUE TITLE
Add toString method for an easier debugging 

### ISSUE THREAD

**Issue by peterjurkovic** [Vonage/vonage-java-sdk#134]
Would be nice to have `toString()` methods across the lib

**Comment by judy2k** [comment]
This is definitely something we need to get better at.

**Comment by cr0wst** [comment]
I'm preferential to `ReflectionToStringBuilder.toString`.  I know reflection can add a bit of overhead, but ideally `toString` is only being used for debugging output.

I also like json reflection using either Gson or Jackson.  The downside with Jackson is you have to catch the exception:
```java
    @Override
    public String toString() {
        try {
            return new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(this);
        } catch (JsonProcessingException jpe) {
            return ReflectionToStringBuilder.reflectionToString(this);
        }
    }
```

**Comment by michel-zimmer** [comment]
Have you considered adding Lombok to this project? This would also be a nice option not just for `toString`, but also as a reduction of boiler plate code for `equals` and `hashCode` and possibly more like constructors and so on. (Unless you do not want this, I'll provide a PR as part of the Hacktoberfest so that you can get an idea how this would look like.)

**Comment by michel-zimmer** [comment]
Feel free to command on my PR (linked above)

**Comment by yallen011** [comment]
Yes, I was actually looking into adding Lombok and then completely forgot about it. This looks good. Would you like to continue refactoring this for the rest of the codebase?

**Comment by michel-zimmer** [comment]
Sure, I can do that. Is there a way to test this including the JSON de-/serialization? That way I could possibly simplify the code a lot. (Otherwise I don't feel confident enough, because I could break something.)

**Comment by yallen011** [comment]
We have JUnit tests you can use to make sure existing functionality still works when you change the code. Feel free to add any unit tests you feel you need to add if you don't think the existing test will suffice. Tests are located `src/test` folder. We use gradle so to run the test you can run `./gradlew build` (using the wrapper on a mac) and it will build the code and run the tests or you can do `./gradlew test`. If you are running on a windows machine, that command is `gradlew.bat build` and `gradlew.bat test`. Let me know if you have any more questions. I am here to help.

**Comment by michel-zimmer** [comment]
OK, could you maybe merge the PR? I'd like to build on top of that one, but the PR has been unlinked from my fork and I cannot add new commits.

**Comment by SMadani** [comment]
Given that the repo has evolved significantly, there are no plans to add Lombok or merge the PR at the moment, but adding `toString()`, `equals(Object)` and `hashCode()` are on the roadmap. The aim is to have every public data model class (i.e. requests and responses) implement these in a standardised manner.

**Comment by SMadani** [comment]
Done in #508.
