### ISSUE TITLE
Add possibility to set a request and connection timeout

### ISSUE THREAD

**Issue by peterjurkovic** [Vonage/vonage-java-sdk#136]
Hi there would be really nice to have a possibility to set a connection and request timeouts values. Not sure whats are the default ones?

**Comment by judy2k** [comment]
This should be possible by configuring an `HttpClient` and passing to the `NexmoClient` constructor. But I'd definitely like to look into this more.

**Comment by anmol5varma** [comment]
`    HttpClient client = httpClientConfig.HttpClientObject();

    HttpConfig newConfig = HttpConfig.builder()
      .apiBaseUri(axwayUrl) //Set Your Base API Url here
      .restBaseUri(axwayUrl) //Set your Base Rest Url here
      .build();`

My HttpClient looks like this and .getParams is depricated. How to you propose to make this change in the HttpConfig? @judy2k

**Comment by skagedal** [comment]
Hi! Any updates on this?

**Comment by SMadani** [comment]
Available in v7.8.0 (added in #478).
