### ISSUE TITLE
[Feature request] support alert API

### ISSUE THREAD

**Issue by Toub** [Vonage/vonage-java-sdk#212]
It looks like the current version (3.9.0) does not support the [Alert API]( https://developer.nexmo.com/messaging/us-short-codes/guides/alerts) to be able to send application-to-person (A2P) to USA & Canada.

Is there any plan to implement it in the near future?

**Comment by judy2k** [comment]
Hello @toub. 

It's not currently in our short term plans to implement this - but given that you've requested it, we may be able to do something. Would it be possible to get a quick summary of your use-case?

**Comment by Toub** [comment]
I am currently using nexmo-java client to send various A2M messages to my customers, especially 2FA messages and a few alerts for some of my business customers.

The messages are currently not delivered to Canada because I need to buy a long virtual number. But it is probably not enough, as my message are not bi-directional, so carriers will probably block them is I don't use a short virtual number, using [2FA API](https://developer.nexmo.com/messaging/us-short-codes/guides/2fa) and [Alert API](https://developer.nexmo.com/messaging/us-short-codes/guides/alerts)

Of course, I could implement the API myself, but it would be better if nexmo-java client would support it.

@see https://help.nexmo.com/hc/en-us/articles/204017023
> Carriers will expect traffic to be bi-directional.

**Comment by yallen011** [comment]
as of right now, this API is out of scope, but we will reopen if we add to scope
