### ISSUE TITLE
POJO for NotifyEvent similar to RecordEvent

### ISSUE THREAD

**Issue by sharmasha2nk** [Vonage/vonage-java-sdk#277]

**Comment by yallen011** [comment]
Hi @sharmasha2nk, unlike the Record action, the Notify action doesn't return anything so it doesn't need a NotifyEvent class. Closing this issue since no action is needed.

**Comment by sharmasha2nk** [comment]
Hi @yallen011, not sure why you say it doesn't return anything. For Notify action also will get a request with conversation_uuid, timestamp and payload. 
A class like this should be good enough for most of the cases.
```
class NotifyEvent {
    private String conversationUuid;
    private Date timestamp;
    private Map<String, Object> payload; // @JsonAnyGetter @JsonAnySetter
}
```

**Comment by yallen011** [comment]
Hi @sharmasha2nk I was basing my response off of the docs https://developer.nexmo.com/voice/voice-api/ncco-reference#notify that didn't show any response parameters for this NCCO. I have reopened the ticket.

**Comment by imabhinavagarwal** [comment]
Hi @yallen011 
I would like to work on this. Please let me know if this is open to work.
Thanks
