### ISSUE TITLE
if the client is thread safe?

### ISSUE THREAD

**Issue by a95417079** [Vonage/vonage-java-sdk#290]
if i can init the client only one time?
`static NexmoClient client = new NexmoClient.Builder().build();`

**Comment by yallen011** [comment]
Hi @a95417079 can you give a little bit more details about your actual question or concern.

**Comment by yallen011** [comment]
We will investigate if we are or not and document this accordingly in the README.

**Comment by yallen011** [comment]
Verbiage added to README. We do not currently support thread safety in this SDK
