### ISSUE TITLE
NexmoResponseParseException - Unable to parse exception when terminating calls

### ISSUE THREAD

**Issue by vinokanth92** [Vonage/vonage-java-sdk#295]
I am attempting to terminate a call using `VoiceClient`'s  `modifyCall` method.  I am using an Australian virtual number for testing. The action fails with a bizarre `400 Bad Request` error with a really unhelpful "Unable to parse exception". I tried replicating this issue with an US number but was not successful. So at this moment, I am only able to consistently reproduce this error for an Australian virtual number.

The Nexmo base URL I am using is: `https://api.nexmo.com`. This issue is very similar to https://github.com/Nexmo/nexmo-java/issues/264. Please help me resolve this.
SDK version: `5.3.0` (latest, but this issue still persists in version `5.0.0` too)

Stack trace of the error (Removed redundant lines):
```
com.nexmo.client.NexmoResponseParseException: Unable to parse response.
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:107) ~[client-5.0.0.jar:5.0.0]
	at com.nexmo.client.voice.CallsEndpoint.put(CallsEndpoint.java:101) ~[client-5.0.0.jar:5.0.0]
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:168) ~[client-5.0.0.jar:5.0.0]
	at com.nexmo.client.voice.VoiceClient.modifyCall(VoiceClient.java:151) ~[client-5.0.0.jar:5.0.0]
Caused by: org.apache.http.client.HttpResponseException: status code: 400, reason phrase: Bad Request
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70) ~[httpclient-4.5.10.jar:4.5.10]
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66) ~[httpclient-4.5.10.jar:4.5.10]
	at com.nexmo.client.voice.ModifyCallMethod.parseResponse(ModifyCallMethod.java:65) ~[client-5.0.0.jar:5.0.0]
	at com.nexmo.client.voice.ModifyCallMethod.parseResponse(ModifyCallMethod.java:38) ~[client-5.0.0.jar:5.0.0]
	at com.nexmo.client.AbstractMethod.execute(AbstractMethod.java:103) ~[client-5.0.0.jar:5.0.0]
	... 17 common frames omitted
```

**Comment by yallen011** [comment]
@vinokanth92 are you making a call to another Australian number? if not, what country does the number you are calling reside?

**Comment by vinokanth92** [comment]
@yallen011 The AU virtual number from nexmo is the destination (application). I am calling from an AU mobile number.

**Comment by yallen011** [comment]
@vinokanth92 what type of number what was that virtual number? 
![image](https://user-images.githubusercontent.com/13876064/88974399-90804f00-d286-11ea-85f3-ad80072e5565.png)

**Comment by yallen011** [comment]
Relates to #294

**Comment by vinokanth92** [comment]
@yallen011 The number is a mobile number.

**Comment by yallen011** [comment]
@vinokanth92 are you working behind a proxy?

**Comment by vinokanth92** [comment]
@yallen011 Yes the service is behind a ALB. When testing locally it's behind `ngrok` ssh tunnel.

**Comment by yallen011** [comment]
If you have a proxy, you may need to supply a custom HTTP Client to the Nexmo class that calls the proxy.

Make sure that you can reach https://rest.nexmo.com/sms/json from your development machine or the machine that is getting this error. You can also try our cURL option at https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms/curl to see if even a basic API call works.

**Comment by vinokanth92** [comment]
@yallen011 As I mentioned in the post, it works for any USA number and fails for AU numbers. So I don't think it's issue with custom HTTP client as you pointed out. Could help me understand how this work for USA numbers?

**Comment by vinokanth92** [comment]
@yallen011 And also why do I have to check if SMS API works when the issue is with the call termination issue?

**Comment by yallen011** [comment]
@vinokanth92 sorry, I corrected my earlier response. I used the wrong links. Can you provide me with the Caller ID or to and from numbers and the timestamp of the call that received the error so that I can have support lookup the logs and see what the error was? Thank you. Or would you be willing to hop on a quick call so that I can help you troubleshoot?  Don't have access to an AU number to do an AU to AU(Nexmo Virtual Number) call. I can only do US to AU(Nexmo Virtual Number) calls.

**Comment by vinokanth92** [comment]
Sorry for the late response. I can help you trouble shoot. Please email on vinokanth.velu@gmail.com. Thank you.

**Comment by yallen011** [comment]
@vinokanth92 I pushed a fix in the latest version that should fix the error you are having. If it did not, please feel free to add any additional comments or ask to reopen this ticket with any new errors you may come across with this API call.
