### ISSUE TITLE
[blitz] Remove unnecessary references to the "this" keyword

### ISSUE THREAD

**Issue by yallen011** [Vonage/vonage-java-sdk#305]
There are several files in the SDK that reference _this.variable-name_ where it is only necessary to reference the variable using just the variable name itself. Below is a list of files that need to be changed.

### Instructions
Assign yourself to one of the files listed below by commenting with the name of the file you are going to work on, assign yourself to the PR, then link the PR you create to this issue

### Files

- [x] [AccountClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/AccountClient.java)

- [x] [PrefixPricingEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/PrefixPricingEndpoint.java)

- [x] [PricingEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/PricingEndpoint.java)

- [x] [SecretManagementEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/SecretManagementEndpoint.java)

- [x] [SettingsEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/SettingsEndpoint.java)

- [x] [TopUpEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/account/TopUpEndpoint.java)

- [x] [Messages.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/capabilities/Messages.java)

- [x] [Rtc.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/capabilities/Rtc.java)

- [x] [Voice.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/capabilities/Voice.java)

- [x] [Application.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/Application.java)

- [ ] [ApplicationClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/ApplicationClient.java)

- [ ] [ApplicationEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/ApplicationEndpoint.java)

- [ ] [ListApplicationRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/application/ListApplicationRequest.java)

- [x] [AuthCollection.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/auth/AuthCollection.java)

- [ ] [JWTAuthMethod.java)](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/auth/JWTAuthMethod.java)

- [x] [TokenAuthMethod.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/auth/TokenAuthMethod.java)

- [ ] [VonageUnacceptableAuthException.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/auth/VonageUnacceptableAuthException.java)

- [ ] [ConversionClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/conversion/ConversionClient.java)

- [ ] [ConversionEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/conversion/ConversionEndpoint.java)

- [ ] [AdvancedInsightRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/insight/AdvancedInsightRequest.java)

- [ ] [BasicInsightRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/insight/BasicInsightRequest.java)

- [ ] [InsightClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/insight/InsightClient.java)

- [ ] [StandardInsightRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/insight/StandardInsightRequest.java)

- [ ] [XmlParser.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/legacyutils/XmlParser.java)

- [x] [NumbersClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/numbers/NumbersClient.java)

- [ ] [SearchNumbersEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/numbers/SearchNumbersEndpoint.java)

- [ ] [UpdateNumberRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/numbers/UpdateNumberRequest.java)

- [ ] [RedactClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/redact/RedactClient.java)

- [ ] [RedactEndpoint.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/redact/RedactEndpoint.java)

- [ ] [MO.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/callback/messages/MO.java)

- [ ] [AbstractMOServlet.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/callback/AbstractMOServlet.java)

- [ ] [BinaryMessage.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/messages/BinaryMessage.java)

- [x] [WapPushMessage.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/messages/WapPushMessage.java)

- [ ] [MessageStatus.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/MessageStatus.java)

- [ ] [SearchRejectedMessagesRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SearchRejectedMessagesRequest.java)

- [ ] [SmsClient.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SmsClient.java)

- [x] [SmsDateSearchRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SmsDateSearchRequest.java)

- [ ] [SmsIdSearchRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SmsIdSearchRequest.java)

- [x] [SmsSubmissionResponse.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SmsSubmissionResponse.java)

- [ ] [SmsSubmissionResponseMessage.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/SmsSubmissionResponseMessage.java)

- [ ] [SnsRequest.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sns/request/SnsRequest.java)

- [ ] [SnsResponse.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sns/response/SnsResponse.java)

- [ ] [SnsSubscribeResponse.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java)

- [ ] [](url)

**Comment by dinitrogen-tetroxide** [comment]
I would like to work on VonageClient.java.

**Comment by ThanoshanMV** [comment]
I would like to work on HttpWrapper.java

**Comment by WorkInProgress-Development** [comment]
Apologies if I am missing something obvious, but there doesn't seem to be a list of files on this issue.

**Comment by yallen011** [comment]
@WorkInProgress-Development sorry, I haven't added them yet. I was still getting some of the Issues setup for Hacktoberfest. But you are more than welcome to go through the repo and if you find one that you want to work on, just comment here so that others will know that file is taken and won't try to submit a PR for the same change.

**Comment by ThanoshanMV** [comment]
@yallen011 , I would like to work on AccountClient.java, PrefixPricingEndpoint.java, PricingEndpoint.java, SecretManagementEndpoint.java, SettingsEndpoint.java, TopUpEndpoint.java, Messages.java, Rtc.java, Voice.java, Application.java, ApplicationClient.java, ApplicationEndpoint.java, ListApplicationRequest.java, AuthCollection.java, JWTAuthMethod.java, TokenAuthMethod.java

**Comment by Hitesh77** [comment]
Hi @yallen011

I would like to work in the following classes:

- SnsSubscribeResponse.java
- SnsResponse.java
- SnsRequest.java
- SmsSubmissionResponseMessage.java

Thanks

**Comment by poornapragna877** [comment]
I would like to Work on BasicInsightRequest.java

**Comment by imabhinavagarwal** [comment]
Hi @yallen011 
I would like to work on ApplicationClient.java and ApplicationEndpoint.java
Thanks

**Comment by malakar-soham** [comment]
I would like to work on [BinaryMessage.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/messages/BinaryMessage.java)

**Comment by WesleyBrenno** [comment]
I would like to work on 

- XmlParser.java
- NumbersClient.java
- SearchNumbersEndpoint.java
- UpdateNumberRequest.java
- RedactClient.java
- RedactEndpoint.java

**Comment by hbheroi** [comment]
I would like to work on: 

- RedactClient.java
- RedactEndpoint.java
- MO.java
- AbstractMOServlet.java

**Comment by SanchitaMishra170676** [comment]
I would like to work on SmsClient.java

**Comment by malakar-swastik** [comment]
I would like to work on [WapPushMessage.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sms/messages/WapPushMessage.java)

**Comment by Prassud** [comment]
I would like to work on below files

 Messages.java

 Rtc.java

 Voice.java

 Application.java

**Comment by Prassud** [comment]
I would like to work on below files

- Messages.java

-  Rtc.java

-  Voice.java

-  Application.java

**Comment by Keenal** [comment]
I'd like to contribute, if any files are still left.

**Comment by Hitesh77** [comment]
Hi All,

I am contributing to open source for the first and getting a 403(forbidden error) error can anyone please help me out on this.

Thanks in Advance.

**Comment by imabhinavagarwal** [comment]
Hi @Hitesh77 
Have you forked the repo or are you trying to push in main repo?
P.S.: You can ask in discord to get faster response. Here is the link https://discord.gg/hacktoberfest

**Comment by Hitesh77** [comment]
Hi @imabhinavagarwal,

Thank you so much for your help, I haven't forked the repo but now after fork, I'm not getting a 403 error.

**Comment by Keenal** [comment]
I'd like to take the following files:

ListApplicationRequest.java
AuthCollection.java
JWTAuthMethod.java
TokenAuthMethod.java
ConversionClient.java
ConversionEndpoint.java

**Comment by berry120** [comment]
Hello,

I'd like to take SmsSubmissionResponse.java.

**Comment by henry398** [comment]
Hi! I'd like to work on TokenAuthMethod.java

**Comment by sophieml** [comment]
I'd like to work on `AuthCollection.java`!

**Comment by ILGO0413** [comment]
I'd like to work on:
JWTAuthMethod.java
VonageUnacceptableAuthException.java
ConversionClient.java
ConversionEndpoint.java
AdvancedInsightRequest.java

**Comment by ILGO0413** [comment]
Also fixed remaining files:
InsightClient.java
StandardInsightRequest.java
MessageStatus.java
SearchRejectedMessagesRequest.java
SmsIdSearchRequest.java

**Comment by yallen011** [comment]
@imabhinavagarwal  thank you so much for hopping in and helping out with  @Hitesh77's question ⭐

**Comment by daniel-shuy** [comment]
I'll take the remaining:
- AuthCollection.java
- SmsDateSearchRequest.java

**Comment by aryanrawlani28** [comment]
Hi!
I'll take `CheckEndpoint.java` & `CheckResponse.java`.
Cheers!

**Comment by Code0987** [comment]
Hey, 

Taking up some extras `HttpConfig.java` `AbstractMethod.java`.

Thanks.
