### ISSUE TITLE
Remove @author Javadoc comment from java files

### ISSUE THREAD

**Issue by yallen011** [Vonage/vonage-java-sdk#308]
We are no longer using the `@author` javadoc comment anymore since we are open source and we use the CONTRIBUTOR.md file now for contributions

Remove **@author <name of author>** from the following files, and any other file that has it that hasn't been listed yet:

- [SnsSubscribeResponse.java](https://github.com/Vonage/vonage-java-sdk/blob/master/src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java)

- [](url)

**Comment by dolphincodes** [comment]
I would like to work on this issue.

**Comment by yallen011** [comment]
Great. Vonage appreciates your contribution. I didn't get a chance to look through the entire repo for all the other files that use it but you can do a search in your IDE to find the rest. 😄

**Comment by ShubhamSood1406** [comment]
Can I also work on this?

**Comment by SanchitaMishra170676** [comment]
I also wanna help with this.

**Comment by rahulaarora** [comment]
I also wanna work on this
