### ISSUE TITLE
Change deprecated testing imports

### ISSUE THREAD

**Issue by sirNikolai** [Vonage/vonage-java-sdk#342]
Should be an improvement but noticed in unit testing that `junit.framework.Assert` is used quite a bit. This has been deprecated for a while https://github.com/junit-team/junit4/issues/473 and since this project is active should transition to non-legacy methods `org.junit.Assert` for better maintainability (or even JUnit 5).

**Comment by yallen011** [comment]
Hi @sirNikolai would you like to submit a PR for this?

**Comment by sirNikolai** [comment]
I think someone else started one. Was more interested in whether it would be a decent idea to move altogether to JUnit 5. Otherwise I wouldn't mind leaving it for someone else since already have a PR for something else out. That said if there are no takers can always circle back and do this over the weekend.

**Comment by yallen011** [comment]
yes, I don't think there are any takers for this so you can totally take this on. The push is to move to JUnit 5. The other PR was centered around a Hacktoberfest issue and not particularly around removing deprecated testing imports. So if you are up for it, I will assign it to you.

**Comment by sirNikolai** [comment]
@yallen011 sure go for it. Can get the fundamentals of it done at least.

**Comment by yallen011** [comment]
Fixed in 6.0.0 release
