### ISSUE TITLE
Generate Signature Method

### ISSUE THREAD

**Issue by baroved1** [Vonage/vonage-java-sdk#359]
![1](https://user-images.githubusercontent.com/78050926/105908931-879ee900-602f-11eb-9fc8-d1b91b9e6338.PNG)
![2](https://user-images.githubusercontent.com/78050926/105908934-88d01600-602f-11eb-9f5b-1d2d442a8035.PNG)

Hello,
I have tried to generate signature from your library – for test my webhook and validate signature.
But I got invalid signature.
I attached my unit test code, What Am I doing wrong ?
I think the data that i send as the first param to GenerateSignature method, it is wrong. 
Thanks!

**Comment by dragonmantank** [comment]
Instructions for manually generating a hash can be found here:

https://developer.nexmo.com/concepts/guides/signing-messages#manually-generate-a-signature

This will let you generate a hash that can be used to validate an incoming SMS webhook. The biggest issue is usually the ordering of the parameters.

The above instructions only work for the SMS/Messaging API. This does not apply to the newer Messages API (which supports Facebook, WhatsApp, SMS, and more) as it uses a different authentication method. You will also need to make sure that you have contacted support and they have enabled webhook signatures for your account. Enabling signatures in the dashboard will only enable it for the sending of SMS, not any callbacks we make to your application.

**Comment by slorello89** [comment]
Hi @baroved1 - looks like you posted a .NET question in our Java SDK :) - did you check out the https://github.com/nexmo-community/vonage-aspnetcore library we just published last month? It has a capability for adding a middleware component to validate inbound SMS messages. Also the [InboundSms](https://github.com/Vonage/vonage-dotnet-sdk/blob/master/Vonage/Messaging/InboundSms.cs#L61) class has a ValidateSignature method you can use.

**Comment by baroved1** [comment]
yes, I use in ValidateSignature Method but i get false(Invalid Signature), I think i am missing something when i use in generateSignature Method.

**Comment by slorello89** [comment]
closing as this issue was opened in the .NET SDKs repo.
