### ISSUE TITLE
JWT signature issue

### ISSUE THREAD

**Issue by nilaydave38** [Vonage/vonage-java-sdk#360]
Hello,

I am getting below error:-
`Caused by: java.lang.NoSuchMethodError: io.jsonwebtoken.JwtBuilder.signWith(Ljava/security/Key;Lio/jsonwebtoken/SignatureAlgorithm;)Lio/jsonwebtoken/JwtBuilder;`

I had included Vonage client dependency as described in **readme** file:-
`
		<dependency>
		      <groupId>com.vonage</groupId>
		      <artifactId>client</artifactId>
		      <version>6.1.0</version>
		</dependency>`
		
I had tried several way to solve it but still this issue coming.
Here is the code which cased issue:-
`VonageClient client = VonageClient.builder()
		        .applicationId(APP_ID)
		        .privateKeyPath(KEY_FILE)
		        .build();
		log.info("Making call");
		Call call = new Call(toNumber, fromNumber,
                "https://nexmo-community.github.io/ncco-examples/connect-phone.json");
		CallEvent event = client.getVoiceClient().createCall(call);`		
		
Please help me where I am wrong and what I am missing.
Thank you

**Comment by slorello89** [comment]
Hi @nilaydave38 

Sounds like your project isn't pulling in io.jsonwebtoken - which is a dependency of nexmo jwt library that the vonage-java-sdk uses to generate web-tokens - can you validate your pom file isn't pulling in a different version? https://github.com/Nexmo/nexmo-jwt-jdk/blob/main/pom.xml#L72 - see here for what we use. May want to make sure that it's being restored properly and the appropriate symbols are being put on your class path.

**Comment by nilaydave38** [comment]
> Hi @nilaydave38
> 
> Sounds like your project isn't pulling in io.jsonwebtoken - which is a dependency of nexmo jwt library that the vonage-java-sdk uses to generate web-tokens - can you validate your pom file isn't pulling in a different version? https://github.com/Nexmo/nexmo-jwt-jdk/blob/main/pom.xml#L72 - see here for what we use. May want to make sure that it's being restored properly and the appropriate symbols are being put on your class path.

Hello @slorello89 
Thank you for your response :)
I already included that too :)
Here it is in current pom.xml:-

> 
		
		<dependency>
		      <groupId>com.vonage</groupId>
		      <artifactId>client</artifactId>
		      <version>6.1.0</version>
		</dependency>
		





		
		





		





		
		<dependency>
		  <groupId>com.nexmo</groupId>
		  <artifactId>jwt</artifactId>
		  <version>1.0.1</version>
		</dependency>		

		
Even I tried to add dependency separately also like below:-

> 

		<dependency>
		      <groupId>com.vonage</groupId>
		      <artifactId>client</artifactId>
		      <version>6.1.0</version>
		</dependency>
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-impl</artifactId>
		    <version>0.11.2</version>		    
		</dependency>
		
		
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-api</artifactId>
		    <version>0.11.2</version>		    
		</dependency>
		
		<dependency>
		    <groupId>io.jsonwebtoken</groupId>
		    <artifactId>jjwt-jackson</artifactId>
		    <version>0.11.2</version>		    
		</dependency>
		


But that also didn't work for me (:
I need to solve this as on urgent basis but I don't get any solution yet (:

**Comment by nilaydave38** [comment]
Hello @slorello89 

Any update for this issue?
I tried a lot and doubt that issue maybe with the token generated by Vonage, still not sure.
Even I tried with other websites for a key generation but they are giving **Base64 illegal character exception for decoding** so will you please tell me which website I would refer for key generation and in which format Vonage Client will take that key?
Or if you can share keys which I can try?

Thank you :)

**Comment by slorello89** [comment]
Hi @nilaydave38 - can you share with me an example project where this is happening? I can't reproduce it on my end.

thanks,

**Comment by nilaydave38** [comment]
> Hi @nilaydave38 - can you share with me an example project where this is happening? I can't reproduce it on my end.
> 
> thanks,

Hello @slorello89 
Thank you for your response :)
I finally got the solution for that issue :) That issue coming because of some dependency conflicts. I successfully get solved **(Finally).** 
But now I want to make an app like any two global mobile number (person) can connect via Vonage and can talk to each other.
I did not get any example to do that with Java SDK.
Do you have any link where I can get idea how two-person can talk to each other via Vonage Java SDK?
Also, I tried with **"connect JSON"** which is given here **https://nexmo-community.github.io/ncco-examples/connect-phone.json** but the call could not connect two numbers and call instantly get disconnected **(in 1s precisely)**.

Currently, I am using free/demo credit account in Vonage for voice API, so do I need to upgrade it to implement that?
Here is the code I am using for connecting two numbers:-

```

VonageClient client = VonageClient.builder()
		        .applicationId("******fd93")
		        .privateKeyPath("*//private_3.key")
		        .build();
		log.info("Making call");
		Call call = new Call(toNumber, fromNumber,"https://nexmo-community.github.io/ncco-examples/connect-phone.json");
		CallEvent callEvent = client.getVoiceClient().createCall(call);
		log.info("Done ", callEvent);		
		} catch (Exception e) {
			log.error("Exception while making call ",e);
			e.printStackTrace();
		} 

```

**Comment by slorello89** [comment]
Hi @nilaydave38 - sort of figured it was a dependency conflict so that makes sense - do you happen to know which dependency, in particular, was causing it so we know for posterity?


RE your question - we have a very similar use case laid out here: https://developer.nexmo.com/use-cases/private-voice-communication - this will let you build a voice proxy between two numbers. This demo is shown in javascript, but it should be pretty easy to translate over to java using this SDK - here's a sample of the [connect action](https://developer.nexmo.com/voice/voice-api/code-snippets/connect-an-inbound-call/java) in java that you'll be reliant on to accomplish this. You shouldn't need two Vonage numbers to accomplish this for your demo, so your free trial should suffice (obviously if you exhaust your credit you'll need to upgrade). When you are rolling this out to an international crowd you will need to ensure that you have voice numbers that can handle different localities - for that you will need a paid account.

As the original issue has been resolved I will be closing this issue, if you have questions regarding your use case feel free to ask them in our [community slack](https://developer.nexmo.com/community/slack) - and please let us know what the conflict was.

**Comment by nilaydave38** [comment]
> Hi @nilaydave38 - sort of figured it was a dependency conflict so that makes sense - do you happen to know which dependency, in particular, was causing it so we know for posterity?
> 
> RE your question - we have a very similar use case laid out here: https://developer.nexmo.com/use-cases/private-voice-communication - this will let you build a voice proxy between two numbers. This demo is shown in javascript, but it should be pretty easy to translate over to java using this SDK - here's a sample of the [connect action](https://developer.nexmo.com/voice/voice-api/code-snippets/connect-an-inbound-call/java) in java that you'll be reliant on to accomplish this. You shouldn't need two Vonage numbers to accomplish this for your demo, so your free trial should suffice (obviously if you exhaust your credit you'll need to upgrade). When you are rolling this out to an international crowd you will need to ensure that you have voice numbers that can handle different localities - for that you will need a paid account.
> 
> As the original issue has been resolved I will be closing this issue if you have questions regarding your use case feel free to ask them in our [community slack](https://developer.nexmo.com/community/slack) - and please let us know what the conflict was.

Hello @slorello89 
The same JWT token functionality is used by spring security to generate token and in that older version of **JJWT** dependency used so I had to exclude it so now working fine :)

And yes thank you for your guidance and support I will check it and if have any doubts that ask in community slack, thank you for sharing that URL :)
