### ISSUE TITLE
Getting missed call instead of rining

### ISSUE THREAD

**Issue by saggammahesh** [Vonage/vonage-java-sdk#371]
Hi Team,
I've just onboarded to Vonage and tried to integrate with voice api.  Sometimes, May be 2 out of 10 times I'm getting a missed call, Basically it's not ringing, just getting a missed call.
Here is the code snippet i'm using. please let me know if anything i'm doing wrongly. 
![image](https://user-images.githubusercontent.com/7000621/133918640-1a72e80d-426b-46ed-80bf-505908a281e6.png)

**Comment by SMadani** [comment]
This is most likely a concurrency issue in your program, since you're sometimes getting a call and sometimes not. The snippet posted here seems fine.
