### ISSUE TITLE
Need jdk1.7 compatible vonage-client jar

### ISSUE THREAD

**Issue by skaluva** [Vonage/vonage-java-sdk#372]
Hi,
We are planning to use vonage-client jar for validating incoming message. But it seems it is compatible with JDK 1.8. But unfortunately, we are still using JDK1.7 on our servers. I tried to build source code using JDK1.7 but its not working.
Can you please suggest if there is a way to get JDK1.7 compatible jar?

**Comment by SMadani** [comment]
Hello,
As Java 7 is [officially end of life](https://www.oracle.com/java/technologies/java-se-support-roadmap.html), we do not currently support it. We recommend that you upgrade to at least Java 8, preferably Java 17 if possible as that is the latest long-term support release.
