### ISSUE TITLE
Incorrect link to javadocs in ReadMe

### ISSUE THREAD

**Issue by virginiaprivacycoalition** [Vonage/vonage-java-sdk#426]
In the usage section of the readme for this repository, there is the following mention of the Javadocs for this SDK  and a link to view them. 
![image](https://user-images.githubusercontent.com/69700676/206253470-7a4d72ca-cdb6-4850-95da-176c74f84966.png)
However, this link is for the URL "http://vonage.github.io/vonage-java-sdk/" which returns a 404 error code, even if the protocol is changed to HTTPS.

![image](https://user-images.githubusercontent.com/69700676/206254009-e471ac0a-5ea0-46db-b443-cb1466fc2a74.png)

Anyway, I would have just submitted a PR to fix the link, but I cannot find the Vonage Java SDK javadocs online anywhere for the life of me.

**Comment by SMadani** [comment]
Thank you for reporting this. The Javadocs are not hosted anywhere, but your IDE should provide documentation automatically for the SDK if you download sources. If you'd like to browse the Javadocs for reference, you can use a service like `javadoc.io`. For more detailed documentation on our APIs and how to use them, please see our [developer portal](https://developer.vonage.com/documentation).
