### ISSUE TITLE
Support for Jakarta APIs v6

### ISSUE THREAD

**Issue by mmoayyed** [Vonage/vonage-java-sdk#457]
**Describe the bug**

This is not a bug :) 

I see the library here intends to use the `javax` namespace in various areas, in particular inside the `RequestSigning` class. This of course causes `NoClassDefFoundError` type of errors for Jakarta v6 since APIs have moved onto the `jakarta` namespace. 

Is Jakarta v6 something you might be interested to support and handle perhaps in `7.4.0`? 

**To Reproduce**

```java
var client = VonageClient.builder()
            .apiKey(vonage.getApiToken())
            .apiSecret(vonage.getApiSecret())
            .signatureSecret(vonage.getSignatureSecret())
            .httpConfig(HttpConfig.defaultConfig())
            .applicationId(vonage.getApplicationId())
            .hashType(HashUtil.HashType.valueOf(vonage.getHashType()))
            .build();
```

**Expected behavior**

Avoid `NoClassDefFoundError` errors where the SDK here is able to properly support jakarta APIs v6. 

**Screenshots**

Error logs:

```
java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
	at com.vonage.client.auth.SignatureAuthMethod.apply(SignatureAuthMethod.java:43)
	at com.vonage.client.AbstractMethod.applyAuth(AbstractMethod.java:111)
	at com.vonage.client.AbstractMethod.execute(AbstractMethod.java:71)
	at com.vonage.client.sms.SmsClient.submitMessage(SmsClient.java:62)
```

**Vonage SDK Version**
 - Version: 7.3.0

**Java SDK Version**
- Version: 17

**Proxy Server Used**
 * [ ] Yes
 * [X] No
 
**Context**

I would like to try out this SDK inside a Spring Boot 3.1.x application w/ Apache Tomcat 10, which only do support Jakarta v6.

**Comment by SMadani** [comment]
Thank you for raising this. The only issue I can see is that [Jakarta 6 requires Java 11](https://jakarta.ee/specifications/servlet/6.0/). To ensure the widest compatibility, we want to support Java 8 for as long as possible. I'm open to suggestions for workarounds. One of these would be to remove the dependency on `javax.servlet` altogether.

**Comment by mmoayyed** [comment]
Thanks much! 

I agree that removing the dependency altogether would be ideal. Some in-between compromises could also be to perhaps separate support for javax and jakarta into separate modules and let the developer choose, or, programmatically determine which API is on the classpath and dynamically instantiate and use that instead. (Though admittedly, both of these solutions seem like they would be a lot more work than just dropping the dependency, and feel like they might be worse than the problem! )

**Comment by SMadani** [comment]
I've deprecated it and made it an optional `compileOnly` dependency, so hopefully that helps. In the next major version the dependency will probably be removed altogether. 7.4.0 has just been released so give it a try :)

**Comment by mmoayyed** [comment]
At any rate, I'll keep an eye out for the next major release. As long as statements such as `import javax.servlet.http.HttpServletRequest;` exist, I will run into the same problem. Thank you for taking care of this scenario so far!
