### ISSUE TITLE
Application API Voice capability is missing several features

### ISSUE THREAD

**Issue by davideberlein** [Vonage/vonage-java-sdk#465]
**Describe the bug**
According to your [official REST documentation](https://developer.vonage.com/en/api/application.v2#getApplication) several fields are missing in the Java Client SDK:
- `Webhook.Type` model is missing the `fallback_answer_url ` type
- This prevents setting the webhook for `com.vonage.client.application.capabilities.Voice`
- `com.vonage.client.application.Application` model is missing the `privacy.improve_ai ` field

Additionally it seems like the Application REST API  doesn't provide a way to specify the following fields for the Voice Capability even though they are present on the Admin Web UI:
- `Region` 
- `Signed Webhooks` flag
- `Conversation TTL`

**Expected behavior**
The fields are present on the models and the builders.

**Vonage SDK Version**
 - Version: 7.6.0

**Java SDK Version**
- Version: 11

**Comment by SMadani** [comment]
Thank you for reporting this - I will aim to fix this in the next release :)

**Comment by SMadani** [comment]
Fixed in v7.7.0.
