### ISSUE TITLE
VoiceClient.modifyCall requires UUID to contain dashes even though these are not supported by the backend

### ISSUE THREAD

**Issue by davideberlein** [Vonage/vonage-java-sdk#469]
**Describe the bug**
com.vonage.client.voice.VoiceClient.modifyCall(String, ModifyCallAction) in line 194 contains the code:
```java
validateUuid(uuid)
```
This method requires the UUID to contain the `-` symbol which however
a.) are not present on any of the call UUIDs I receive from the webhooks
b.) are not even supported by the the server. If I added the "missing" `-` symbols the REST endpoint returns a `404` whereas if I call the REST endpoint without the `-` symbols via Postman it works.

**Expected behavior**
The `validateUuid(uuid)` should be removed because with your current implementation it is literally not possible to call any method on the `VoiceClient` as all of them check for the "valid" UUID.

**Vonage SDK Version**
 - Version: 7.5.0

**Java SDK Version**
- Version: 11

**Proxy Server Used**
 * [ ] Yes
 * [X] No

**Additional context/ Error Log**

**Comment by SMadani** [comment]
Thank you for reporting this. Should be fixed in v7.7.0 (#473).
