### ISSUE TITLE
Several Voice API webhook models are missing

### ISSUE THREAD

**Issue by davideberlein** [Vonage/vonage-java-sdk#475]
**Describe the bug**
While some Voice API Webhook types are present i.e. `InputEvent` and `CallEvent` other events documented here are missing: https://developer.vonage.com/en/voice/voice-api/webhook-reference 
e.g.
- [Answer](https://developer.vonage.com/en/voice/voice-api/webhook-reference#answer-webhook)
- [Completed](https://developer.vonage.com/en/voice/voice-api/webhook-reference#completed)
- [Transfer](https://developer.vonage.com/en/voice/voice-api/webhook-reference#transfer)

**Missing headers field access**
Additionally the existing models don't allow to read SIP header values:
 - For the [Answer Webhook](https://developer.vonage.com/en/voice/voice-api/webhook-reference#answer-webhook) they are directly added to the payload as described here:
https://developer.vonage.com/en/voice/voice-api/webhook-reference#transmitting-additional-data-with-sip-headers 
- For all the [Event Webhooks](https://developer.vonage.com/en/voice/voice-api/webhook-reference#event-webhook) they are in a `headers` field holding key/value's

**Vonage SDK Version**
 - Version: 7.7

**Java SDK Version**
- Version: 11

**Comment by SMadani** [comment]
Thanks again for reporting this. Will aim to have a fix soon™️.

**Comment by SMadani** [comment]
Fixed in #506, will be released in v8.2.0.
