### ISSUE TITLE
ModifyCallEndpoint returns null on a HTTP 400 error instead of throwing an exception

### ISSUE THREAD

**Issue by davideberlein** [Vonage/vonage-java-sdk#476]
**Describe the bug**
The `ModifyCallEndpoint` class of the `VoiceClient` doesn't properly check the response of the HTTP call. It checks for a `200` code and returns `null` for all other cases.

The code should be changed as follows:
1. explicitly check for `200` like it now does
2. additionally check for `204` and return a `null` only for that case.
3. In all other cases an Exception should be thrown.

I guess there are other Endpoint implementations that also don't do this right.

**To Reproduce**
call `VoiceClient.transferCall()` with an invalid UUID.

**Expected behavior**
An exception is thrown however the method finishes without Errors.

**Vonage SDK Version**
 - Version: 7.7

**Java SDK Version**
- Version: 11

**Comment by SMadani** [comment]
Thank you for reporting this. You are right that there are other endpoints that are implemented like this. I am planning on refactoring all the supported APIs to have a standardised way of dealing with non-2xx responses where an exception is thrown.
