### ISSUE TITLE
Vonage 7.11.0 makes io.jsonwebtoken unusable

### ISSUE THREAD

**Issue by Lunatix01** [Vonage/vonage-java-sdk#493]
Hey there, as the title says for some reason it makes Jwts unusable when i create an instance of it it returns null.
I use 7.10.0 without a problem, but when i try to update it to 7.11.0 the issue arises.

**To Reproduce**
1. private final JwtParser parser = Jwts.parserBuilder().build(); a single function like this reproduces the error

**Expected behavior**
i expect to return an object of jwtParser

**Screenshots**
![image](https://github.com/Vonage/vonage-java-sdk/assets/56197620/edf55343-9952-4108-ba06-2b23adee5136)

**Vonage SDK Version**
 - Version: 7.11.0

**Java SDK Version**
- Version: 17.0.9

**Proxy Server Used**
 * [ ] No

**Comment by SMadani** [comment]
This is because the [`com.vonage:jwt` library has been upgraded to v1.1.0](https://github.com/Vonage/vonage-jwt-jdk/releases/tag/v1.1.0), which uses `jjwt-api:0.12.3`.
