### ISSUE TITLE
Cannot get conversation message content (GenericEvent package protection)

### ISSUE THREAD

**Issue by jerome25000** [Vonage/vonage-java-sdk#539]
Hello,
using the latest version : 8.9.2

ListEventsRequest request = ListEventsRequest.builder().eventType(EventType.MESSAGE).build();
        ListEventsResponse response = client.listEvents(roomId, request);
        response.getEvents().forEach(e -> {
System.out.printf("%n %s", e.toString()); 

I see output like this
GenericEvent {"type":"message","id":3,"from":"MEM-0052a62c-d0ca-4237-8c59-1fed1edf0e15","timestamp":"2024-07-04T15:32:44.303Z","_embedded":{"from_user":{"id":"USR-5b39d44a-5023-4cad-b0fc-aaf0b9f9f9dc","name":"user9"},"from_member":{"id":"MEM-0052a62c-d0ca-4237-8c59-1fed1edf0e15"}},"body":{"message_type":"text","text":"hello!"}}

But how to display the body here? 

GenericEvent is package protection , not public !

Help, please !

**Comment by SMadani** [comment]
Thanks for reporting. This is fixed in [v8.9.3](https://github.com/Vonage/vonage-java-sdk/releases/tag/v8.9.3).

**Comment by SMadani** [comment]
Note that as of the time of this comment, [OSSRH is down](https://status.maven.org/), preventing the release from being published. It will be available once the service is restored.
