### ISSUE TITLE
 Fully automate release process

### ISSUE THREAD

**Issue by leggetter** [Vonage/vonage-java-sdk#73]
There are [numerous steps](https://github.com/Nexmo/nexmo-java/wiki/Releasing-nexmo-java#release-checklist) to the release process, some of which are manual. Can we improve those steps to ensure that none of them are missed as they were in #72?

**Comment by SMadani** [comment]
Done - now documented under https://confluence.vonage.com/display/DEVREL/Java+SDK+Release+Process
